### ISSUE TITLE
Incorrect image paths

### ISSUE THREAD

**Issue by johngeorgewright** [Vayel/crossbardocs#3]
The images on this page https://github.com/Vayel/crossbardocs/wiki/Architecture are pointing to:

https://raw.githubusercontent.com/wiki/crossbario/crossbar ...

When I **think** they should be pointing to:

https://raw.githubusercontent.com/wiki/Vayel/crossbardocs ...

**Comment by Vayel** [comment]
Thanks for having opened an issue, but this repo is outdated.
